services:
  db:
    image: mysql:8.3.0
    container_name: win_final_db
    restart: always
    environment:
      MYSQL_DATABASE: agri_chain
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uuser", "-ppassword"]
      timeout: 20s
      retries: 10
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d

volumes:
  mysql_data:
